// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI_LIC66S

#ifndef _UI_COMP_CONTAINER20_H
#define _UI_COMP_CONTAINER20_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Container20
#define UI_COMP_CONTAINER20_CONTAINER20 0
#define UI_COMP_CONTAINER20_PANEL42 1
#define UI_COMP_CONTAINER20_PANEL42_LABEL41 2
#define UI_COMP_CONTAINER20_PANEL42_TEXTAREA17 3
#define UI_COMP_CONTAINER20_PANEL39 4
#define UI_COMP_CONTAINER20_PANEL39_LABEL38 5
#define UI_COMP_CONTAINER20_PANEL39_TEXTAREA14 6
#define UI_COMP_CONTAINER20_PANEL40 7
#define UI_COMP_CONTAINER20_PANEL40_LABEL39 8
#define UI_COMP_CONTAINER20_PANEL40_TEXTAREA15 9
#define _UI_COMP_CONTAINER20_NUM 10
lv_obj_t * ui_Container20_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
