// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI_LIC66S

#include "ui.h"

// COMPONENT Container20

lv_obj_t * ui_Container20_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Container20;
    cui_Container20 = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_Container20);
    lv_obj_set_width(cui_Container20, 795);
    lv_obj_set_height(cui_Container20, 295);
    lv_obj_set_x(cui_Container20, 3);
    lv_obj_set_y(cui_Container20, 24);
    lv_obj_set_align(cui_Container20, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Container20, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_Container20, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(cui_Container20, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(cui_Container20, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_Container20, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Panel42;
    cui_Panel42 = lv_obj_create(cui_Container20);
    lv_obj_set_width(cui_Panel42, 320);
    lv_obj_set_height(cui_Panel42, 35);
    lv_obj_set_x(cui_Panel42, 962);
    lv_obj_set_y(cui_Panel42, -115);
    lv_obj_set_align(cui_Panel42, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(cui_Panel42, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Panel42, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Panel42, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Panel42, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_Panel42, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Panel42, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_Panel42, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_Panel42, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Panel42, lv_color_hex(0x00749A), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(cui_Panel42, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_t * cui_Label41;
    cui_Label41 = lv_label_create(cui_Panel42);
    lv_obj_set_width(cui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label41, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_Label41, "SSID:");
    lv_obj_set_style_text_color(cui_Label41, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label41, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_TextArea17;
    cui_TextArea17 = lv_textarea_create(cui_Panel42);
    lv_obj_set_width(cui_TextArea17, 200);
    lv_obj_set_height(cui_TextArea17, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(cui_TextArea17, 140);
    lv_obj_set_y(cui_TextArea17, 0);
    lv_obj_set_align(cui_TextArea17, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(cui_TextArea17, 5);
    lv_textarea_set_placeholder_text(cui_TextArea17, "..................");
    lv_textarea_set_one_line(cui_TextArea17, true);
    lv_obj_clear_flag(cui_TextArea17, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(cui_TextArea17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_TextArea17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_TextArea17, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_TextArea17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_TextArea17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_TextArea17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Panel39;
    cui_Panel39 = lv_obj_create(cui_Container20);
    lv_obj_set_width(cui_Panel39, 320);
    lv_obj_set_height(cui_Panel39, 34);
    lv_obj_set_x(cui_Panel39, 978);
    lv_obj_set_y(cui_Panel39, -183);
    lv_obj_set_align(cui_Panel39, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(cui_Panel39, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Panel39, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Panel39, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Panel39, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_Panel39, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Panel39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_Panel39, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_Panel39, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Panel39, lv_color_hex(0x00749A), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(cui_Panel39, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_t * cui_Label38;
    cui_Label38 = lv_label_create(cui_Panel39);
    lv_obj_set_width(cui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label38, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_Label38, "Password:");
    lv_obj_set_style_text_color(cui_Label38, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label38, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_TextArea14;
    cui_TextArea14 = lv_textarea_create(cui_Panel39);
    lv_obj_set_width(cui_TextArea14, 200);
    lv_obj_set_height(cui_TextArea14, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(cui_TextArea14, 140);
    lv_obj_set_y(cui_TextArea14, 0);
    lv_obj_set_align(cui_TextArea14, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(cui_TextArea14, 5);
    lv_textarea_set_placeholder_text(cui_TextArea14, "..................");
    lv_textarea_set_one_line(cui_TextArea14, true);
    lv_obj_clear_flag(cui_TextArea14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(cui_TextArea14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_TextArea14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_TextArea14, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_TextArea14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_TextArea14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_TextArea14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Panel40;
    cui_Panel40 = lv_obj_create(cui_Container20);
    lv_obj_set_width(cui_Panel40, 320);
    lv_obj_set_height(cui_Panel40, 35);
    lv_obj_set_x(cui_Panel40, 1546);
    lv_obj_set_y(cui_Panel40, -11);
    lv_obj_set_align(cui_Panel40, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(cui_Panel40, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Panel40, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Panel40, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Panel40, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_Panel40, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Panel40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_Panel40, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_Panel40, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Panel40, lv_color_hex(0x00749A), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(cui_Panel40, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_t * cui_Label39;
    cui_Label39 = lv_label_create(cui_Panel40);
    lv_obj_set_width(cui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label39, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_Label39, "Channel:");
    lv_obj_set_style_text_color(cui_Label39, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label39, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_TextArea15;
    cui_TextArea15 = lv_textarea_create(cui_Panel40);
    lv_obj_set_width(cui_TextArea15, 200);
    lv_obj_set_height(cui_TextArea15, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(cui_TextArea15, 140);
    lv_obj_set_y(cui_TextArea15, 0);
    lv_obj_set_align(cui_TextArea15, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(cui_TextArea15, 5);
    lv_textarea_set_placeholder_text(cui_TextArea15, "..................");
    lv_textarea_set_one_line(cui_TextArea15, true);
    lv_obj_clear_flag(cui_TextArea15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(cui_TextArea15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_TextArea15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_TextArea15, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_TextArea15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_TextArea15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_TextArea15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINER20_NUM);
    children[UI_COMP_CONTAINER20_CONTAINER20] = cui_Container20;
    children[UI_COMP_CONTAINER20_PANEL42] = cui_Panel42;
    children[UI_COMP_CONTAINER20_PANEL42_LABEL41] = cui_Label41;
    children[UI_COMP_CONTAINER20_PANEL42_TEXTAREA17] = cui_TextArea17;
    children[UI_COMP_CONTAINER20_PANEL39] = cui_Panel39;
    children[UI_COMP_CONTAINER20_PANEL39_LABEL38] = cui_Label38;
    children[UI_COMP_CONTAINER20_PANEL39_TEXTAREA14] = cui_TextArea14;
    children[UI_COMP_CONTAINER20_PANEL40] = cui_Panel40;
    children[UI_COMP_CONTAINER20_PANEL40_LABEL39] = cui_Label39;
    children[UI_COMP_CONTAINER20_PANEL40_TEXTAREA15] = cui_TextArea15;
    lv_obj_add_event_cb(cui_Container20, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Container20, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Container20_create_hook(cui_Container20);
    return cui_Container20;
}

