// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI_LIC66S

#include "ui.h"

void ui_event_comp_DeviceINFO1_DeviceINFO1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_DeviceINFO1 = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(comp_DeviceINFO1[UI_COMP_DEVICEINFO1_DEVICEINFO1], LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_screen_change(&ui_SCRconfigdevice, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SCRconfigdevice_screen_init);
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_state_modify(comp_DeviceINFO1[UI_COMP_DEVICEINFO1_DEVICEINFO1], LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

// COMPONENT DeviceINFO1

lv_obj_t * ui_DeviceINFO1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_DeviceINFO1;
    cui_DeviceINFO1 = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_DeviceINFO1, 710);
    lv_obj_set_height(cui_DeviceINFO1, 40);
    lv_obj_set_align(cui_DeviceINFO1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_DeviceINFO1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_DeviceINFO1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_DeviceINFO1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_DeviceINFO1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_DeviceINFO1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_DeviceINFO1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_DeviceINFO1, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_DeviceINFO1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_DeviceINFO1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_DeviceINFO1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_DeviceINFO1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_DeviceINFO1, lv_color_hex(0x00536D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(cui_DeviceINFO1, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_t * cui_DeviceID2;
    cui_DeviceID2 = lv_label_create(cui_DeviceINFO1);
    lv_obj_set_width(cui_DeviceID2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_DeviceID2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_DeviceID2, -300);
    lv_obj_set_y(cui_DeviceID2, 0);
    lv_obj_set_align(cui_DeviceID2, LV_ALIGN_CENTER);
    lv_label_set_text(cui_DeviceID2, "Device ID");
    lv_obj_set_style_text_color(cui_DeviceID2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_DeviceID2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_DeviceID2, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_LocalID2;
    cui_LocalID2 = lv_label_create(cui_DeviceINFO1);
    lv_obj_set_width(cui_LocalID2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LocalID2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_LocalID2, -170);
    lv_obj_set_y(cui_LocalID2, 0);
    lv_obj_set_align(cui_LocalID2, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LocalID2, "Local ID");
    lv_obj_set_style_text_color(cui_LocalID2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_LocalID2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_LocalID2, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_NumDevice2;
    cui_NumDevice2 = lv_label_create(cui_DeviceINFO1);
    lv_obj_set_width(cui_NumDevice2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_NumDevice2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_NumDevice2, -10);
    lv_obj_set_y(cui_NumDevice2, 0);
    lv_obj_set_align(cui_NumDevice2, LV_ALIGN_CENTER);
    lv_label_set_text(cui_NumDevice2, "Number Device");
    lv_obj_set_style_text_color(cui_NumDevice2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_NumDevice2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_NumDevice2, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_MAC3;
    cui_MAC3 = lv_label_create(cui_DeviceINFO1);
    lv_obj_set_width(cui_MAC3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_MAC3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_MAC3, 190);
    lv_obj_set_y(cui_MAC3, 0);
    lv_obj_set_align(cui_MAC3, LV_ALIGN_CENTER);
    lv_label_set_text(cui_MAC3, "MAC");
    lv_obj_set_style_text_color(cui_MAC3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_MAC3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_MAC3, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_MAC4;
    cui_MAC4 = lv_label_create(cui_DeviceINFO1);
    lv_obj_set_width(cui_MAC4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_MAC4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_MAC4, 310);
    lv_obj_set_y(cui_MAC4, 0);
    lv_obj_set_align(cui_MAC4, LV_ALIGN_CENTER);
    lv_label_set_text(cui_MAC4, "Time");
    lv_obj_set_style_text_color(cui_MAC4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_MAC4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_MAC4, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_DEVICEINFO1_NUM);
    children[UI_COMP_DEVICEINFO1_DEVICEINFO1] = cui_DeviceINFO1;
    children[UI_COMP_DEVICEINFO1_DEVICEID2] = cui_DeviceID2;
    children[UI_COMP_DEVICEINFO1_LOCALID2] = cui_LocalID2;
    children[UI_COMP_DEVICEINFO1_NUMDEVICE2] = cui_NumDevice2;
    children[UI_COMP_DEVICEINFO1_MAC3] = cui_MAC3;
    children[UI_COMP_DEVICEINFO1_MAC4] = cui_MAC4;
    lv_obj_add_event_cb(cui_DeviceINFO1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_DeviceINFO1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_DeviceINFO1, ui_event_comp_DeviceINFO1_DeviceINFO1, LV_EVENT_ALL, children);
    ui_comp_DeviceINFO1_create_hook(cui_DeviceINFO1);
    return cui_DeviceINFO1;
}

