// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI_LIC66S

#include "ui.h"

void Scan_Licene(lv_event_t * e)
{
	// Your code here
}

void Rescan_Licene(lv_event_t * e)
{
	// Your code here
}

void Newscan_Licene(lv_event_t * e)
{
	// Your code here
}

void Setlicene(lv_event_t * e)
{
	// Your code here
}

void configdevice(lv_event_t * e)
{
	// Your code here
}
