// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI_LIC66S

#include "ui.h"

lv_obj_t * ui_SCRconfigdevice2 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Panel40 = NULL;
lv_obj_t * ui_Label42 = NULL;
lv_obj_t * ui_Label43 = NULL;
lv_obj_t * ui_Container19 = NULL;
lv_obj_t * ui_Panel41 = NULL;
lv_obj_t * ui_Label40 = NULL;
lv_obj_t * ui_TextArea16 = NULL;
lv_obj_t * ui_Panel43 = NULL;
lv_obj_t * ui_Label44 = NULL;
lv_obj_t * ui_TextArea18 = NULL;
lv_obj_t * ui_Panel44 = NULL;
lv_obj_t * ui_Label45 = NULL;
lv_obj_t * ui_TextArea19 = NULL;
lv_obj_t * ui_Keyboard7 = NULL;
lv_obj_t * ui_Container18 = NULL;
lv_obj_t * ui_Container20 = NULL;
lv_obj_t * ui_Panel33 = NULL;
lv_obj_t * ui_Panel38 = NULL;
lv_obj_t * ui_Label36 = NULL;
// event funtions
void ui_event_Panel40(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_Panel40, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_state_modify(ui_Panel40, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_screen_change(&ui_SCRconfigdevice, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SCRconfigdevice_screen_init);
    }
}

void ui_event_Panel41(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_Panel44, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard7,  ui_TextArea16);
        _ui_flag_modify(ui_Keyboard7, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_state_modify(ui_Panel43, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Panel41, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
}

void ui_event_Panel43(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_Panel44, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard7,  ui_TextArea18);
        _ui_flag_modify(ui_Keyboard7, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_state_modify(ui_Panel43, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_Panel41, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_Panel44(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_Panel44, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_keyboard_set_target(ui_Keyboard7,  ui_TextArea19);
        _ui_flag_modify(ui_Keyboard7, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_state_modify(ui_Panel43, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Panel41, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_Keyboard7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_state_modify(ui_Panel44, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Panel43, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Panel41, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_flag_modify(ui_Keyboard7, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Panel33(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        opaon_Animation(ui_Panel33, 0);
        _ui_state_modify(ui_Panel38, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_RELEASED) {
        opaoff_Animation(ui_Panel33, 0);
        _ui_state_modify(ui_Panel38, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        configdevice(e);
    }
}

// build funtions

void ui_SCRconfigdevice2_screen_init(void)
{
    ui_SCRconfigdevice2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SCRconfigdevice2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_SCRconfigdevice2, &ui_img_settings_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_img_create(ui_SCRconfigdevice2);
    lv_img_set_src(ui_Image7, &ui_img_settings_corner_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image7, 353);
    lv_obj_set_y(ui_Image7, -212);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel40 = lv_obj_create(ui_Image7);
    lv_obj_set_width(ui_Panel40, 30);
    lv_obj_set_height(ui_Panel40, 30);
    lv_obj_set_x(ui_Panel40, 20);
    lv_obj_set_y(ui_Panel40, 0);
    lv_obj_set_align(ui_Panel40, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel40, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel40, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel40, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Panel40, &ui_img_icn_x_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel40, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Panel40, &ui_img_icn_x_png, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_Panel40, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_Panel40, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label42 = lv_label_create(ui_SCRconfigdevice2);
    lv_obj_set_width(ui_Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label42, -336);
    lv_obj_set_y(ui_Label42, -206);
    lv_obj_set_align(ui_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label42, "LIC66S");
    lv_obj_set_style_text_color(ui_Label42, lv_color_hex(0xCECECE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label42, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label42, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label43 = lv_label_create(ui_SCRconfigdevice2);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label43, -269);
    lv_obj_set_y(ui_Label43, -134);
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label43, "Config device");
    lv_obj_set_style_text_color(ui_Label43, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label43, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label43, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container19 = lv_obj_create(ui_SCRconfigdevice2);
    lv_obj_remove_style_all(ui_Container19);
    lv_obj_set_width(ui_Container19, 795);
    lv_obj_set_height(ui_Container19, 64);
    lv_obj_set_x(ui_Container19, 1);
    lv_obj_set_y(ui_Container19, -73);
    lv_obj_set_align(ui_Container19, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container19, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container19, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container19, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container19, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container19, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel41 = lv_obj_create(ui_Container19);
    lv_obj_set_width(ui_Panel41, 250);
    lv_obj_set_height(ui_Panel41, 35);
    lv_obj_set_x(ui_Panel41, 1085);
    lv_obj_set_y(ui_Panel41, -115);
    lv_obj_set_align(ui_Panel41, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Panel41, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel41, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel41, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel41, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel41, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel41, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel41, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel41, lv_color_hex(0x00749A), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Panel41, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label40 = lv_label_create(ui_Panel41);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label40, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label40, "SSID:");
    lv_obj_set_style_text_color(ui_Label40, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label40, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea16 = lv_textarea_create(ui_Panel41);
    lv_obj_set_width(ui_TextArea16, 200);
    lv_obj_set_height(ui_TextArea16, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextArea16, 100);
    lv_obj_set_y(ui_TextArea16, 0);
    lv_obj_set_align(ui_TextArea16, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea16, 5);
    lv_textarea_set_placeholder_text(ui_TextArea16, "............................");
    lv_textarea_set_one_line(ui_TextArea16, true);
    lv_obj_clear_flag(ui_TextArea16, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_TextArea16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea16, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TextArea16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel43 = lv_obj_create(ui_Container19);
    lv_obj_set_width(ui_Panel43, 250);
    lv_obj_set_height(ui_Panel43, 34);
    lv_obj_set_x(ui_Panel43, 978);
    lv_obj_set_y(ui_Panel43, -183);
    lv_obj_set_align(ui_Panel43, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Panel43, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel43, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel43, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel43, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel43, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel43, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel43, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel43, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel43, lv_color_hex(0x00749A), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Panel43, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label44 = lv_label_create(ui_Panel43);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label44, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label44, "Password:");
    lv_obj_set_style_text_color(ui_Label44, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label44, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label44, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea18 = lv_textarea_create(ui_Panel43);
    lv_obj_set_width(ui_TextArea18, 200);
    lv_obj_set_height(ui_TextArea18, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextArea18, 100);
    lv_obj_set_y(ui_TextArea18, 0);
    lv_obj_set_align(ui_TextArea18, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea18, 10);
    lv_textarea_set_placeholder_text(ui_TextArea18, "............................");
    lv_textarea_set_one_line(ui_TextArea18, true);
    lv_obj_clear_flag(ui_TextArea18, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_TextArea18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea18, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TextArea18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel44 = lv_obj_create(ui_Container19);
    lv_obj_set_width(ui_Panel44, 250);
    lv_obj_set_height(ui_Panel44, 35);
    lv_obj_set_x(ui_Panel44, 1546);
    lv_obj_set_y(ui_Panel44, -11);
    lv_obj_set_align(ui_Panel44, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Panel44, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel44, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel44, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel44, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel44, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel44, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel44, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel44, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel44, lv_color_hex(0x00749A), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Panel44, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label45 = lv_label_create(ui_Panel44);
    lv_obj_set_width(ui_Label45, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label45, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label45, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label45, "Channel:");
    lv_obj_set_style_text_color(ui_Label45, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label45, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label45, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea19 = lv_textarea_create(ui_Panel44);
    lv_obj_set_width(ui_TextArea19, 200);
    lv_obj_set_height(ui_TextArea19, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextArea19, 100);
    lv_obj_set_y(ui_TextArea19, 0);
    lv_obj_set_align(ui_TextArea19, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea19, 5);
    lv_textarea_set_placeholder_text(ui_TextArea19, "............................");
    lv_textarea_set_one_line(ui_TextArea19, true);
    lv_obj_clear_flag(ui_TextArea19, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_TextArea19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea19, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TextArea19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard7 = lv_keyboard_create(ui_SCRconfigdevice2);
    lv_obj_set_width(ui_Keyboard7, 694);
    lv_obj_set_height(ui_Keyboard7, 256);
    lv_obj_set_x(ui_Keyboard7, -4);
    lv_obj_set_y(ui_Keyboard7, -24);
    lv_obj_set_align(ui_Keyboard7, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Keyboard7, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_Keyboard7, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Keyboard7, 10, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Keyboard7, lv_color_hex(0x002835), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard7, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Keyboard7, LV_BLEND_MODE_ADDITIVE, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Keyboard7, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Keyboard7, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Keyboard7, &lv_font_montserrat_30, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_Container18 = lv_obj_create(ui_SCRconfigdevice2);
    lv_obj_remove_style_all(ui_Container18);
    lv_obj_set_width(ui_Container18, 336);
    lv_obj_set_height(ui_Container18, 51);
    lv_obj_set_x(ui_Container18, 2);
    lv_obj_set_y(ui_Container18, -53);
    lv_obj_set_align(ui_Container18, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_Container18, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container18, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container18, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container18, -10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container20 = lv_obj_create(ui_Container18);
    lv_obj_remove_style_all(ui_Container20);
    lv_obj_set_width(ui_Container20, 120);
    lv_obj_set_height(ui_Container20, 50);
    lv_obj_set_align(ui_Container20, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container20, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel33 = lv_obj_create(ui_Container20);
    lv_obj_set_width(ui_Panel33, 100);
    lv_obj_set_height(ui_Panel33, 30);
    lv_obj_set_align(ui_Panel33, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel33, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel33, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel33, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel33, lv_color_hex(0x00ACFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel33, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel33, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel33, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel38 = lv_obj_create(ui_Container20);
    lv_obj_set_width(ui_Panel38, 100);
    lv_obj_set_height(ui_Panel38, 30);
    lv_obj_set_align(ui_Panel38, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel38, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel38, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel38, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel38, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel38, lv_color_hex(0x0083EF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_Panel38, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_Panel38, lv_color_hex(0x00BCDD), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Panel38, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label36 = lv_label_create(ui_Panel38);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "Set");

    lv_obj_add_event_cb(ui_Panel40, ui_event_Panel40, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel41, ui_event_Panel41, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel43, ui_event_Panel43, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel44, ui_event_Panel44, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboard7, ui_event_Keyboard7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel33, ui_event_Panel33, LV_EVENT_ALL, NULL);

}

void ui_SCRconfigdevice2_screen_destroy(void)
{
    if(ui_SCRconfigdevice2) lv_obj_del(ui_SCRconfigdevice2);

    // NULL screen variables
    ui_SCRconfigdevice2 = NULL;
    ui_Image7 = NULL;
    ui_Panel40 = NULL;
    ui_Label42 = NULL;
    ui_Label43 = NULL;
    ui_Container19 = NULL;
    ui_Panel41 = NULL;
    ui_Label40 = NULL;
    ui_TextArea16 = NULL;
    ui_Panel43 = NULL;
    ui_Label44 = NULL;
    ui_TextArea18 = NULL;
    ui_Panel44 = NULL;
    ui_Label45 = NULL;
    ui_TextArea19 = NULL;
    ui_Keyboard7 = NULL;
    ui_Container18 = NULL;
    ui_Container20 = NULL;
    ui_Panel33 = NULL;
    ui_Panel38 = NULL;
    ui_Label36 = NULL;

}
