// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI_LIC66S

#ifndef UI_SCRSETTING_H
#define UI_SCRSETTING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SCRSetting
extern void ui_SCRSetting_screen_init(void);
extern void ui_SCRSetting_screen_destroy(void);
extern lv_obj_t * ui_SCRSetting;
extern lv_obj_t * ui_Image8;
extern void ui_event_Panel49(lv_event_t * e);
extern lv_obj_t * ui_Panel49;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Container22;
extern void ui_event_Panel46(lv_event_t * e);
extern lv_obj_t * ui_Panel46;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_TextArea14;
extern void ui_event_Panel39(lv_event_t * e);
extern lv_obj_t * ui_Panel39;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_TextArea11;
extern void ui_event_Panel42(lv_event_t * e);
extern lv_obj_t * ui_Panel42;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_TextArea12;
extern void ui_event_Keyboard6(lv_event_t * e);
extern lv_obj_t * ui_Keyboard6;
extern lv_obj_t * ui_Container24;
extern lv_obj_t * ui_Container21;
extern void ui_event_Panel48(lv_event_t * e);
extern lv_obj_t * ui_Panel48;
extern lv_obj_t * ui_Panel45;
extern lv_obj_t * ui_Label41;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

