// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI_LIC66S

#ifndef UI_SCRCONFIGDEVICE2_H
#define UI_SCRCONFIGDEVICE2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SCRconfigdevice2
extern void ui_SCRconfigdevice2_screen_init(void);
extern void ui_SCRconfigdevice2_screen_destroy(void);
extern lv_obj_t * ui_SCRconfigdevice2;
extern lv_obj_t * ui_Image7;
extern void ui_event_Panel40(lv_event_t * e);
extern lv_obj_t * ui_Panel40;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_Container19;
extern void ui_event_Panel41(lv_event_t * e);
extern lv_obj_t * ui_Panel41;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui_TextArea16;
extern void ui_event_Panel43(lv_event_t * e);
extern lv_obj_t * ui_Panel43;
extern lv_obj_t * ui_Label44;
extern lv_obj_t * ui_TextArea18;
extern void ui_event_Panel44(lv_event_t * e);
extern lv_obj_t * ui_Panel44;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_TextArea19;
extern void ui_event_Keyboard7(lv_event_t * e);
extern lv_obj_t * ui_Keyboard7;
extern lv_obj_t * ui_Container18;
extern lv_obj_t * ui_Container20;
extern void ui_event_Panel33(lv_event_t * e);
extern lv_obj_t * ui_Panel33;
extern lv_obj_t * ui_Panel38;
extern lv_obj_t * ui_Label36;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

