// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI_LIC66S

#include "ui.h"

lv_obj_t * ui_SCRSetting = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Panel49 = NULL;
lv_obj_t * ui_Label34 = NULL;
lv_obj_t * ui_Label35 = NULL;
lv_obj_t * ui_Container22 = NULL;
lv_obj_t * ui_Panel46 = NULL;
lv_obj_t * ui_Label39 = NULL;
lv_obj_t * ui_TextArea14 = NULL;
lv_obj_t * ui_Panel39 = NULL;
lv_obj_t * ui_Label30 = NULL;
lv_obj_t * ui_TextArea11 = NULL;
lv_obj_t * ui_Panel42 = NULL;
lv_obj_t * ui_Label37 = NULL;
lv_obj_t * ui_TextArea12 = NULL;
lv_obj_t * ui_Keyboard6 = NULL;
lv_obj_t * ui_Container24 = NULL;
lv_obj_t * ui_Container21 = NULL;
lv_obj_t * ui_Panel48 = NULL;
lv_obj_t * ui_Panel45 = NULL;
lv_obj_t * ui_Label41 = NULL;
// event funtions
void ui_event_Panel49(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_Panel49, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_state_modify(ui_Panel49, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_screen_change(&ui_HOME, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HOME_screen_init);
    }
}

void ui_event_Panel46(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_Panel46, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_keyboard_set_target(ui_Keyboard6,  ui_TextArea14);
        _ui_flag_modify(ui_Keyboard6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_state_modify(ui_Panel42, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Panel39, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_Panel39(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_Panel39, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_keyboard_set_target(ui_Keyboard6,  ui_TextArea11);
        _ui_flag_modify(ui_Keyboard6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_state_modify(ui_Panel42, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Panel46, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_Panel42(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_Panel39, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard6,  ui_TextArea12);
        _ui_flag_modify(ui_Keyboard6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_state_modify(ui_Panel42, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_Panel39, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_Keyboard6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_state_modify(ui_Panel39, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Panel46, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Panel42, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_flag_modify(ui_Keyboard6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Panel48(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        opaon_Animation(ui_Panel48, 0);
        _ui_state_modify(ui_Panel45, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_RELEASED) {
        opaoff_Animation(ui_Panel48, 0);
        _ui_state_modify(ui_Panel45, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        configdevice(e);
    }
}

// build funtions

void ui_SCRSetting_screen_init(void)
{
    ui_SCRSetting = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SCRSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_SCRSetting, &ui_img_settings_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_img_create(ui_SCRSetting);
    lv_img_set_src(ui_Image8, &ui_img_settings_corner_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image8, 353);
    lv_obj_set_y(ui_Image8, -212);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel49 = lv_obj_create(ui_Image8);
    lv_obj_set_width(ui_Panel49, 30);
    lv_obj_set_height(ui_Panel49, 30);
    lv_obj_set_x(ui_Panel49, 20);
    lv_obj_set_y(ui_Panel49, 0);
    lv_obj_set_align(ui_Panel49, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel49, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel49, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel49, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Panel49, &ui_img_icn_x_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel49, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Panel49, &ui_img_icn_x_png, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_Panel49, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_Panel49, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label34 = lv_label_create(ui_SCRSetting);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label34, -336);
    lv_obj_set_y(ui_Label34, -206);
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "LIC66S");
    lv_obj_set_style_text_color(ui_Label34, lv_color_hex(0xCECECE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label34, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label35 = lv_label_create(ui_SCRSetting);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label35, -269);
    lv_obj_set_y(ui_Label35, -134);
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "Setting");
    lv_obj_set_style_text_color(ui_Label35, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label35, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container22 = lv_obj_create(ui_SCRSetting);
    lv_obj_remove_style_all(ui_Container22);
    lv_obj_set_width(ui_Container22, 789);
    lv_obj_set_height(ui_Container22, 69);
    lv_obj_set_x(ui_Container22, -3);
    lv_obj_set_y(ui_Container22, -72);
    lv_obj_set_align(ui_Container22, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container22, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container22, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container22, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container22, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container22, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel46 = lv_obj_create(ui_Container22);
    lv_obj_set_width(ui_Panel46, 250);
    lv_obj_set_height(ui_Panel46, 35);
    lv_obj_set_x(ui_Panel46, 1085);
    lv_obj_set_y(ui_Panel46, -115);
    lv_obj_set_align(ui_Panel46, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Panel46, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel46, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel46, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel46, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel46, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel46, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel46, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel46, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel46, lv_color_hex(0x00749A), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Panel46, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label39 = lv_label_create(ui_Panel46);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label39, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label39, "SSID:");
    lv_obj_set_style_text_color(ui_Label39, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label39, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea14 = lv_textarea_create(ui_Panel46);
    lv_obj_set_width(ui_TextArea14, 200);
    lv_obj_set_height(ui_TextArea14, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextArea14, 100);
    lv_obj_set_y(ui_TextArea14, 0);
    lv_obj_set_align(ui_TextArea14, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea14, 5);
    lv_textarea_set_placeholder_text(ui_TextArea14, "............................");
    lv_textarea_set_one_line(ui_TextArea14, true);
    lv_obj_clear_flag(ui_TextArea14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_TextArea14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea14, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TextArea14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel39 = lv_obj_create(ui_Container22);
    lv_obj_set_width(ui_Panel39, 250);
    lv_obj_set_height(ui_Panel39, 34);
    lv_obj_set_x(ui_Panel39, 978);
    lv_obj_set_y(ui_Panel39, -183);
    lv_obj_set_align(ui_Panel39, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Panel39, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel39, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel39, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel39, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel39, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel39, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel39, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel39, lv_color_hex(0x00749A), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Panel39, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label30 = lv_label_create(ui_Panel39);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label30, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label30, "Password:");
    lv_obj_set_style_text_color(ui_Label30, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label30, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea11 = lv_textarea_create(ui_Panel39);
    lv_obj_set_width(ui_TextArea11, 200);
    lv_obj_set_height(ui_TextArea11, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextArea11, 100);
    lv_obj_set_y(ui_TextArea11, 0);
    lv_obj_set_align(ui_TextArea11, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea11, 10);
    lv_textarea_set_placeholder_text(ui_TextArea11, "............................");
    lv_textarea_set_one_line(ui_TextArea11, true);
    lv_obj_clear_flag(ui_TextArea11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_TextArea11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea11, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TextArea11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel42 = lv_obj_create(ui_Container22);
    lv_obj_set_width(ui_Panel42, 250);
    lv_obj_set_height(ui_Panel42, 35);
    lv_obj_set_x(ui_Panel42, 1546);
    lv_obj_set_y(ui_Panel42, -11);
    lv_obj_set_align(ui_Panel42, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Panel42, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel42, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel42, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel42, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel42, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel42, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel42, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel42, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel42, lv_color_hex(0x00749A), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Panel42, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label37 = lv_label_create(ui_Panel42);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label37, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label37, "Channel:");
    lv_obj_set_style_text_color(ui_Label37, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label37, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea12 = lv_textarea_create(ui_Panel42);
    lv_obj_set_width(ui_TextArea12, 200);
    lv_obj_set_height(ui_TextArea12, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextArea12, 102);
    lv_obj_set_y(ui_TextArea12, -3);
    lv_obj_set_align(ui_TextArea12, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea12, 5);
    lv_textarea_set_placeholder_text(ui_TextArea12, "............................");
    lv_textarea_set_one_line(ui_TextArea12, true);
    lv_obj_clear_flag(ui_TextArea12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_TextArea12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea12, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TextArea12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard6 = lv_keyboard_create(ui_SCRSetting);
    lv_obj_set_width(ui_Keyboard6, 694);
    lv_obj_set_height(ui_Keyboard6, 256);
    lv_obj_set_x(ui_Keyboard6, 18);
    lv_obj_set_y(ui_Keyboard6, -27);
    lv_obj_set_align(ui_Keyboard6, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Keyboard6, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_Keyboard6, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Keyboard6, 10, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Keyboard6, lv_color_hex(0x002835), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard6, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Keyboard6, LV_BLEND_MODE_ADDITIVE, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Keyboard6, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Keyboard6, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Keyboard6, &lv_font_montserrat_30, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_Container24 = lv_obj_create(ui_SCRSetting);
    lv_obj_remove_style_all(ui_Container24);
    lv_obj_set_width(ui_Container24, 336);
    lv_obj_set_height(ui_Container24, 51);
    lv_obj_set_x(ui_Container24, 2);
    lv_obj_set_y(ui_Container24, -53);
    lv_obj_set_align(ui_Container24, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_Container24, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container24, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container24, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container24, -10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container21 = lv_obj_create(ui_Container24);
    lv_obj_remove_style_all(ui_Container21);
    lv_obj_set_width(ui_Container21, 120);
    lv_obj_set_height(ui_Container21, 50);
    lv_obj_set_align(ui_Container21, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container21, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel48 = lv_obj_create(ui_Container21);
    lv_obj_set_width(ui_Panel48, 100);
    lv_obj_set_height(ui_Panel48, 30);
    lv_obj_set_align(ui_Panel48, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel48, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel48, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel48, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel48, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel48, lv_color_hex(0x00ACFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel48, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel48, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel48, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel48, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel45 = lv_obj_create(ui_Container21);
    lv_obj_set_width(ui_Panel45, 100);
    lv_obj_set_height(ui_Panel45, 30);
    lv_obj_set_align(ui_Panel45, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel45, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel45, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel45, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel45, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel45, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel45, lv_color_hex(0x0083EF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_Panel45, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_Panel45, lv_color_hex(0x00BCDD), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Panel45, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label41 = lv_label_create(ui_Panel45);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "Set");

    lv_obj_add_event_cb(ui_Panel49, ui_event_Panel49, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel46, ui_event_Panel46, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel39, ui_event_Panel39, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel42, ui_event_Panel42, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboard6, ui_event_Keyboard6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel48, ui_event_Panel48, LV_EVENT_ALL, NULL);

}

void ui_SCRSetting_screen_destroy(void)
{
    if(ui_SCRSetting) lv_obj_del(ui_SCRSetting);

    // NULL screen variables
    ui_SCRSetting = NULL;
    ui_Image8 = NULL;
    ui_Panel49 = NULL;
    ui_Label34 = NULL;
    ui_Label35 = NULL;
    ui_Container22 = NULL;
    ui_Panel46 = NULL;
    ui_Label39 = NULL;
    ui_TextArea14 = NULL;
    ui_Panel39 = NULL;
    ui_Label30 = NULL;
    ui_TextArea11 = NULL;
    ui_Panel42 = NULL;
    ui_Label37 = NULL;
    ui_TextArea12 = NULL;
    ui_Keyboard6 = NULL;
    ui_Container24 = NULL;
    ui_Container21 = NULL;
    ui_Panel48 = NULL;
    ui_Panel45 = NULL;
    ui_Label41 = NULL;

}
